name: Plugin Test

on:
  pull_request:
    branches:
      - master
      - develop
      - branch-*

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.2', '7.3', '7.4']
        wp-versions: ['latest']
  
    name: WP ${{ matrix.wp-versions }} with PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}.
    
    env:
      IMAGIFY_TESTS_API_KEY: ${{ secrets.IMAGIFY_TESTS_API_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none  # XDebug can be enabled here 'coverage: xdebug'
        tools: composer:v1
    
    - name: Start mysql service
      run: sudo /etc/init.d/mysql start
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-scripts

    - name: Install tests
      run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:3306 $WP_VERSION

    - name: Test
      run: composer run-tests
